WinWaitActive("EnglishEdge LAN Install Program")
Sleep(2000)
ControlFocus("EnglishEdge LAN Install Program","","&Next >")
Sleep(2000)
ControlClick("EnglishEdge LAN Install Program","","&Next >")
Sleep(2000)
ControlFocus("EnglishEdge LAN Install Program","","&Next >")
Sleep(2000)
ControlClick("EnglishEdge LAN Install Program","","&Next >")
Sleep(2000)
ControlFocus("EnglishEdge LAN Install Program","","&Yes")
Sleep(2000)
ControlClick("EnglishEdge LAN Install Program","","&Yes")
Sleep(2000)
ControlFocus("EnglishEdge LAN Install Program","","&Start")
Sleep(2000)
ControlClick("EnglishEdge LAN Install Program","","&Start")
Local $i=1;
Do
sleep($i=$i+1)
ControlFocus("EnglishEdge LAN Install Program","","E&xit")
Until (ControlFocus("EnglishEdge LAN Install Program","","E&xit")=1)
Sleep(2000)
ControlClick("EnglishEdge LAN Install Program","","E&xit")